// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IYUFXDyzXgLep4TAcm2fqGtlqpCGizo',
    appId: '1:8887176167:web:93cc1cfb8af5f716c6cb42',
    messagingSenderId: '8887176167',
    projectId: 'imeditatii',
    authDomain: 'imeditatii.firebaseapp.com',
    storageBucket: 'imeditatii.firebasestorage.app',
    measurementId: 'G-FDM7KLFYEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASKRHG7sYndU6Klhq2B4cHexdBT37LGw8',
    appId: '1:8887176167:android:2fe257f5eab823d0c6cb42',
    messagingSenderId: '8887176167',
    projectId: 'imeditatii',
    storageBucket: 'imeditatii.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4EPz6OhXXgLHbZzMbidGND03wc7yHd1c',
    appId: '1:8887176167:ios:1862fce858291cfbc6cb42',
    messagingSenderId: '8887176167',
    projectId: 'imeditatii',
    storageBucket: 'imeditatii.firebasestorage.app',
    androidClientId: '8887176167-hh7dmn52n1u7k2hp7s6fe5997o8oh4lo.apps.googleusercontent.com',
    iosClientId: '8887176167-o8pmg2oj6jscnp2vbt4kf9iianulrh1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.avochat',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4EPz6OhXXgLHbZzMbidGND03wc7yHd1c',
    appId: '1:8887176167:ios:1862fce858291cfbc6cb42',
    messagingSenderId: '8887176167',
    projectId: 'imeditatii',
    storageBucket: 'imeditatii.firebasestorage.app',
    androidClientId: '8887176167-hh7dmn52n1u7k2hp7s6fe5997o8oh4lo.apps.googleusercontent.com',
    iosClientId: '8887176167-o8pmg2oj6jscnp2vbt4kf9iianulrh1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.avochat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZi5_qb75yKwbh4qd0t3HMdUojKSRI2ic',
    appId: '1:8887176167:web:c5c21e227f7e1367c6cb42',
    messagingSenderId: '8887176167',
    projectId: 'imeditatii',
    authDomain: 'imeditatii.firebaseapp.com',
    storageBucket: 'imeditatii.firebasestorage.app',
    measurementId: 'G-HNEETEXQDK',
  );
}
