// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbTk0OSXxpApbA9XggU5DGdgZwmDjSiqM',
    appId: '1:896891711392:web:41d3e5e608868682137ec5',
    messagingSenderId: '896891711392',
    projectId: 'avochat-b6288',
    authDomain: 'avochat-b6288.firebaseapp.com',
    storageBucket: 'avochat-b6288.firebasestorage.app',
    measurementId: 'G-ZZB6W4HVRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRrQ1a5Xz5Qznh0ugA492WHJiE-CW2t_E',
    appId: '1:896891711392:android:344e94b2b23a1edd137ec5',
    messagingSenderId: '896891711392',
    projectId: 'avochat-b6288',
    storageBucket: 'avochat-b6288.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7TzUlsUtFiTtbNr5REHg_H6DO9GEJP90',
    appId: '1:896891711392:ios:7296b67acbb7dbbf137ec5',
    messagingSenderId: '896891711392',
    projectId: 'avochat-b6288',
    storageBucket: 'avochat-b6288.firebasestorage.app',
    androidClientId: '896891711392-pdgiv6o934tsa5dkh8jm8dvfag455tv2.apps.googleusercontent.com',
    iosClientId: '896891711392-leei0u8lemskpfma1dvmvcmhs6r5u4bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.avochat',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7TzUlsUtFiTtbNr5REHg_H6DO9GEJP90',
    appId: '1:896891711392:ios:7296b67acbb7dbbf137ec5',
    messagingSenderId: '896891711392',
    projectId: 'avochat-b6288',
    storageBucket: 'avochat-b6288.firebasestorage.app',
    androidClientId: '896891711392-pdgiv6o934tsa5dkh8jm8dvfag455tv2.apps.googleusercontent.com',
    iosClientId: '896891711392-leei0u8lemskpfma1dvmvcmhs6r5u4bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.avochat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbTk0OSXxpApbA9XggU5DGdgZwmDjSiqM',
    appId: '1:896891711392:web:a9543caf9f1a2f47137ec5',
    messagingSenderId: '896891711392',
    projectId: 'avochat-b6288',
    authDomain: 'avochat-b6288.firebaseapp.com',
    storageBucket: 'avochat-b6288.firebasestorage.app',
    measurementId: 'G-712W1CNSR8',
  );
}
