import 'package:flutter/material.dart';
import 'app_colors.dart';

class ResourcesData {
  static const String defaultAuthor = "Ahmad Arnaoute";
  static const String defaultRole = "FOUNDER & ADMIN";
  static const String defaultDate = "18.09.2026";

  static final List<Map<String, dynamic>> allArticles = [
    // =========================================================================
    // CLASA A 9-A (15 ARTICOLE)
    // =========================================================================
    {
      "id": "py-9-intro",
      "subject": "PYTHON",
      "grade": "9",
      "module": "1. BAZE PYTHON",
      "title": "Introducere în Python & Scurt Istoric",
      "desc": "Arhitectura interpretorului, compilare vs. interpretare, tipare dinamică și funcția print().",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "4 MIN",
      "color": AppColors.forest,
      "tag": "INTRO",
    },
    {
      "id": "py-9-vars",
      "subject": "PYTHON",
      "grade": "9",
      "module": "1. BAZE PYTHON",
      "title": "Variabile, Tipuri Primitive & input()",
      "desc": "Tipuri fundamentale (int, float, str, bool), conversii de tip (type casting) și citirea cu input().",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "5 MIN",
      "color": AppColors.sky,
      "tag": "SINTAXĂ",
    },
    {
      "id": "py-9-operators",
      "subject": "PYTHON",
      "grade": "9",
      "module": "1. BAZE PYTHON",
      "title": "Operatori Aritmetici & Logici în Python",
      "desc": "Împărțirea întreagă (//), modulo (%), exponențierea (**) și operatorii logici and, or, not.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "5 MIN",
      "color": AppColors.mustard,
      "tag": "OPERATORI",
    },
    {
      "id": "py-9-if",
      "subject": "PYTHON",
      "grade": "9",
      "module": "2. STRUCTURI DE CONTROL (PYTHON)",
      "title": "Instrucțiunea Decizională: if, elif, else",
      "desc": "Ramificări condiționale, operatori de comparare și indentarea obligatorie conform PEP 8.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "5 MIN",
      "color": AppColors.sunset,
      "tag": "CONTROL",
    },
    {
      "id": "py-9-loops",
      "subject": "PYTHON",
      "grade": "9",
      "module": "2. STRUCTURI DE CONTROL (PYTHON)",
      "title": "Structuri Repetitive: while & for range()",
      "desc": "Bucle cu număr cunoscut sau necunoscut de pași. Utilizarea funcției range(), break și continue.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.forest,
      "tag": "BUCLE",
    },
    {
      "id": "cpp-9-intro",
      "subject": "C++",
      "grade": "9",
      "module": "3. BAZE C++",
      "title": "Directiva #include, iostream & cin/cout",
      "desc": "Structura unui program C++, spațiul de nume std și fluxurile de intrare/ieșire din bibliotecă.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "4 MIN",
      "color": AppColors.sky,
      "tag": "C++ I/O",
    },
    {
      "id": "cpp-9-types",
      "subject": "C++",
      "grade": "9",
      "module": "3. BAZE C++",
      "title": "Tipuri de Date, Operatori & Codul ASCII",
      "desc": "Tipul char, conversii implicite/explicite, împărțirea întreagă și operatorul modulo (%).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.mustard,
      "tag": "SINTAXĂ",
    },
    {
      "id": "cpp-9-if-switch",
      "subject": "C++",
      "grade": "9",
      "module": "4. STRUCTURI DE CONTROL (C++)",
      "title": "Instrucțiunile if-else și switch",
      "desc": "Evaluarea condițiilor compuse, acoladele ca delimitator de bloc și instrucțiunea switch-case.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "5 MIN",
      "color": AppColors.sunset,
      "tag": "CONTROL",
    },
    {
      "id": "cpp-9-loops",
      "subject": "C++",
      "grade": "9",
      "module": "4. STRUCTURI DE CONTROL (C++)",
      "title": "Buclele while, do-while și for în C++",
      "desc": "Structuri cu test inițial vs test final. Cum prevenim buclele infinite și când folosim break/continue.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.forest,
      "tag": "BUCLE",
    },
    {
      "id": "alg-9-digits",
      "subject": "C++",
      "grade": "9",
      "module": "5. ALGORITMI ELEMENTARI",
      "title": "Prelucrarea Cifrelor unui Număr",
      "desc": "Descompunerea cifrelor cu % 10 și / 10, construirea oglinditului și verificarea palindroamelor.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "5 MIN",
      "color": AppColors.sky,
      "tag": "ALGORITMI",
    },
    {
      "id": "alg-9-divisors",
      "subject": "C++",
      "grade": "9",
      "module": "5. ALGORITMI ELEMENTARI",
      "title": "Divizibilitate, Numere Prime & Descompunere",
      "desc": "Determinarea divizorilor în O(sqrt(N)), testul de primalitate și descompunerea în factori primi.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.mustard,
      "tag": "ALGORITMI",
    },
    {
      "id": "alg-9-gcd",
      "subject": "C++",
      "grade": "9",
      "module": "5. ALGORITMI ELEMENTARI",
      "title": "CMMDC & Algoritmul lui Euclid",
      "desc": "Algoritmul prin scăderi repetate vs algoritmul rapid prin împărțiri, calculul CMMMC.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "4 MIN",
      "color": AppColors.sunset,
      "tag": "ALGORITMI",
    },
    {
      "id": "cpp-9-vectors-basic",
      "subject": "C++",
      "grade": "9",
      "module": "6. VECTORI (TABLOURI UNIDIMENSIONALE)",
      "title": "Vectori în C++: Declarare, Citire & Parcurgere",
      "desc": "Indexare de la 0 la n-1, determinarea maximului/minimului și inversarea elementelor.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.forest,
      "tag": "VECTORI",
    },
    {
      "id": "cpp-9-vectors-sort",
      "subject": "C++",
      "grade": "9",
      "module": "6. VECTORI (TABLOURI UNIDIMENSIONALE)",
      "title": "Sortarea Vectorilor: BubbleSort & Selecție",
      "desc": "Metode clasice de sortare în O(N^2), interschimbarea valorilor și căutarea binară pe vector sortat.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.sky,
      "tag": "SORTARE",
    },
    {
      "id": "mat-9-quad",
      "subject": "MATEMATICĂ",
      "grade": "9",
      "module": "7. MATEMATICĂ (ALGEBRĂ CLASA A 9-A)",
      "title": "Funcția de Gradul II, Delta & Relațiile lui Viète",
      "desc": "Calculul discriminantului (Δ), semnele rădăcinilor, formarea ecuației și studiul monotoniei parabolei.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.mustard,
      "tag": "ALGEBRĂ",
    },

    // =========================================================================
    // CLASA A 10-A (15 ARTICOLE)
    // =========================================================================
    {
      "id": "cpp-10-matrix-basics",
      "subject": "C++",
      "grade": "10",
      "module": "1. TABLOURI BIDIMENSIONALE (MATRICE)",
      "title": "Matrice în C++: Declarare & Parcurgere",
      "desc": "Indexare cu linii (i) și coloane (j), citirea tablourilor bidimensionale și parcurgerea pe contur.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.forest,
      "tag": "MATRICE",
    },
    {
      "id": "cpp-10-matrix-diagonals",
      "subject": "C++",
      "grade": "10",
      "module": "1. TABLOURI BIDIMENSIONALE (MATRICE)",
      "title": "Diagonala Principală, Secundară & Zone Speciale",
      "desc": "Zone delimitate de diagonale (Nord, Sud, Est, Vest), simetria față de axele principale.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.sky,
      "tag": "MATRICE",
    },
    {
      "id": "cpp-10-strings-cstring",
      "subject": "C++",
      "grade": "10",
      "module": "2. ȘIRURI DE CARACTERE",
      "title": "Șiruri în stil C: char[] & Biblioteca cstring",
      "desc": "Caractere terminale '\\0', funcții esențiale: strlen, strcpy, strcat, strcmp, strstr și strtok.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "8 MIN",
      "color": AppColors.mustard,
      "tag": "ȘIRURI",
    },
    {
      "id": "cpp-10-strings-class",
      "subject": "C++",
      "grade": "10",
      "module": "2. ȘIRURI DE CARACTERE",
      "title": "Clasa std::string în C++ Modern",
      "desc": "Operații native cu operatorul +, metodele length(), find(), substr(), erase() și getline().",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sunset,
      "tag": "ȘIRURI",
    },
    {
      "id": "cpp-10-subprog-basics",
      "subject": "C++",
      "grade": "10",
      "module": "3. SUBPROGRAME (FUNCȚII)",
      "title": "Subprograme: Antet, Prototip & Apel",
      "desc": "Modularizarea codului, tipul returnat de funcție, instrucțiunea return și variabile locale vs globale.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "5 MIN",
      "color": AppColors.forest,
      "tag": "FUNCȚII",
    },
    {
      "id": "cpp-10-subprog-params",
      "subject": "C++",
      "grade": "10",
      "module": "3. SUBPROGRAME (FUNCȚII)",
      "title": "Parametri prin Valoare vs. Referință (&)",
      "desc": "Cum modificăm variabilele din apelant, transmiterea vectorilor ca parametri în funcții.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sky,
      "tag": "FUNCȚII",
    },
    {
      "id": "cpp-10-recursion-intro",
      "subject": "C++",
      "grade": "10",
      "module": "4. RECURSIVITATE",
      "title": "Noțiuni de Bază: Ce este Recursivitatea?",
      "desc": "Stiva de apeluri (Call Stack), condiția de oprire (cazul de bază) și riscul de Stack Overflow.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.mustard,
      "tag": "RECURSIVITATE",
    },
    {
      "id": "cpp-10-recursion-classic",
      "subject": "C++",
      "grade": "10",
      "module": "4. RECURSIVITATE",
      "title": "Algoritmi Clasici Recursivi: Factorial, CMMDC, Fibonacci",
      "desc": "Transformarea algoritmilor iterativi în funcții recursive directe.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sunset,
      "tag": "RECURSIVITATE",
    },
    {
      "id": "cpp-10-d&i-intro",
      "subject": "C++",
      "grade": "10",
      "module": "5. DIVIDE ET IMPERA",
      "title": "Tehnica Divide et Impera & Căutarea Binară",
      "desc": "Descompunerea problemei în subprobleme similare, căutarea binară recursivă în O(log N).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.forest,
      "tag": "D&I",
    },
    {
      "id": "cpp-10-d&i-mergesort",
      "subject": "C++",
      "grade": "10",
      "module": "5. DIVIDE ET IMPERA",
      "title": "Sortarea prin Interclasare: MergeSort",
      "desc": "Divizarea tabloului, interclasarea a doi vectori ordonați și complexitatea stabilă O(N log N).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.sky,
      "tag": "SORTARE",
    },
    {
      "id": "cpp-10-d&i-quicksort",
      "subject": "C++",
      "grade": "10",
      "module": "5. DIVIDE ET IMPERA",
      "title": "Sortarea Rapidă: QuickSort",
      "desc": "Alegerea pivotului, partiționarea vectorului și analiza cazului favorabil vs nefavorabil.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.mustard,
      "tag": "SORTARE",
    },
    {
      "id": "cpp-10-struct",
      "subject": "C++",
      "grade": "10",
      "module": "6. TIPURI STRUCTURATE (STRUCT)",
      "title": "Structuri Eterogene în C++: Tipul struct",
      "desc": "Definirea tipurilor de date proprii, vectori de structuri și accesarea câmpurilor cu operatorul punct (.).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "5 MIN",
      "color": AppColors.sunset,
      "tag": "STRUCT",
    },
    {
      "id": "mat-10-powers",
      "subject": "MATEMATICĂ",
      "grade": "10",
      "module": "7. MATEMATICĂ (CLASA A 10-A)",
      "title": "Puteri, Radicali & Logaritmi",
      "desc": "Proprietățile logaritmilor, schimbarea de bază, ecuații exponențiale și logaritmice pentru bac.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.forest,
      "tag": "ALGEBRĂ",
    },
    {
      "id": "mat-10-complex",
      "subject": "MATEMATICĂ",
      "grade": "10",
      "module": "7. MATEMATICĂ (CLASA A 10-A)",
      "title": "Numere Complexe: Forma Algebrică & Modul",
      "desc": "Unitatea imaginară i (i^2 = -1), conjugatul unui număr complex, modulul |z| și ecuații în C.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sky,
      "tag": "ALGEBRĂ",
    },
    {
      "id": "mat-10-combinatorics",
      "subject": "MATEMATICĂ",
      "grade": "10",
      "module": "7. MATEMATICĂ (CLASA A 10-A)",
      "title": "Permutări, Aranjamente & Combinări",
      "desc": "Formule de calcul factorial, binomul lui Newton și calculul probabilităților clasice (fav/pos).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.mustard,
      "tag": "COMBINATORICĂ",
    },

    // =========================================================================
    // CLASA A 11-A (15 ARTICOLE)
    // =========================================================================
    {
      "id": "cpp-11-backtracking-intro",
      "subject": "C++",
      "grade": "11",
      "module": "1. TEHNICA BACKTRACKING",
      "title": "Backtracking: Mecanismul de Căutare cu Revenire",
      "desc": "Reprezentarea soluțiilor sub formă de vector stivă, condiții de validare și condiții de final.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.forest,
      "tag": "BACKTRACKING",
    },
    {
      "id": "cpp-11-backtracking-perm",
      "subject": "C++",
      "grade": "11",
      "module": "1. TEHNICA BACKTRACKING",
      "title": "Generarea Permutărilor cu Backtracking",
      "desc": "Algoritmul clasic de generare a tuturor permutărilor mulțimii {1, 2, ..., n}.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sky,
      "tag": "BACKTRACKING",
    },
    {
      "id": "cpp-11-backtracking-comb",
      "subject": "C++",
      "grade": "11",
      "module": "1. TEHNICA BACKTRACKING",
      "title": "Generarea Combinărilor & Aranjamentelor",
      "desc": "Optimizarea condițiilor de validare pentru a evita soluțiile duplicate și a genera aranjamente.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.mustard,
      "tag": "BACKTRACKING",
    },
    {
      "id": "cpp-11-graphs-matrix",
      "subject": "C++",
      "grade": "11",
      "module": "2. GRAFURI NEORIENTATE",
      "title": "Grafuri Neorientate: Matricea de Adiacență & Grad",
      "desc": "Reprezentarea prin matrice binară simetrică, gradul unui vârf, numărul de muchii și lema strângerilor de mână.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sunset,
      "tag": "GRAFURI",
    },
    {
      "id": "cpp-11-graphs-bfs",
      "subject": "C++",
      "grade": "11",
      "module": "2. GRAFURI NEORIENTATE",
      "title": "Parcurgerea în Lățime a Grafurilor (BFS)",
      "desc": "Determinarea celor mai scurte drumuri în graf neponderat folosind o coadă (queue).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.forest,
      "tag": "PARCURGERE",
    },
    {
      "id": "cpp-11-graphs-dfs",
      "subject": "C++",
      "grade": "11",
      "module": "2. GRAFURI NEORIENTATE",
      "title": "Parcurgerea în Adâncime a Grafurilor (DFS)",
      "desc": "Parcurgerea recursivă a vârfurilor nevizitate și detecția ciclurilor în graf.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sky,
      "tag": "PARCURGERE",
    },
    {
      "id": "cpp-11-graphs-connected",
      "subject": "C++",
      "grade": "11",
      "module": "2. GRAFURI NEORIENTATE",
      "title": "Conexitate & Componente Conexe",
      "desc": "Algoritm de numărare a componentelor conexe și adăugarea numărului minim de muchii pentru conexitate.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.mustard,
      "tag": "GRAFURI",
    },
    {
      "id": "cpp-11-digraphs-intro",
      "subject": "C++",
      "grade": "11",
      "module": "3. GRAFURI ORIENTATE",
      "title": "Grafuri Orientate: Arcuri & Matrice de Adiacență",
      "desc": "Grad interior vs. grad exterior, circuite, drumuri orientate și reprezentare în memorie.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sunset,
      "tag": "GRAFURI",
    },
    {
      "id": "cpp-11-trees-rooted",
      "subject": "C++",
      "grade": "11",
      "module": "4. ARBORI",
      "title": "Arbori cu Rădăcină: Vectorul de Tați & Frunze",
      "desc": "Proprietățile arborelui (N noduri, N-1 muchii, aciclic și conex), determinarea rădăcinii și a frunzelor.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.forest,
      "tag": "ARBORI",
    },
    {
      "id": "cpp-11-dp-intro",
      "subject": "C++",
      "grade": "11",
      "module": "5. PROGRAMARE DINAMICĂ",
      "title": "Programare Dinamică: Memoizare & Recurență",
      "desc": "Diferența față de divide et impera: memorarea stărilor calculate pentru a evita recalculările inutile.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.sky,
      "tag": "DINAMICĂ",
    },
    {
      "id": "cpp-11-dp-subseq",
      "subject": "C++",
      "grade": "11",
      "module": "5. PROGRAMARE DINAMICĂ",
      "title": "Subșirul Crescător Maximal (LIS)",
      "desc": "Construirea relației de recurență dp[i] și reconstituirea soluției optime în O(N^2).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.mustard,
      "tag": "DINAMICĂ",
    },
    {
      "id": "cpp-11-dp-knapsack",
      "subject": "C++",
      "grade": "11",
      "module": "5. PROGRAMARE DINAMICĂ",
      "title": "Problema Rucsacului Discret (0-1 Knapsack)",
      "desc": "Maximizarea valorii fără a depăși greutatea maximă folosind o matrice de stări dp[i][w].",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "8 MIN",
      "color": AppColors.sunset,
      "tag": "DINAMICĂ",
    },
    {
      "id": "mat-11-matrices",
      "subject": "MATEMATICĂ",
      "grade": "11",
      "module": "6. MATEMATICĂ (CLASA A 11-A)",
      "title": "Algebră Liniară: Operații cu Matrice",
      "desc": "Adunarea matricelor, înmulțirea cu scalar și produsul matricial linie pe coloană.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.forest,
      "tag": "ALGEBRĂ",
    },
    {
      "id": "mat-11-determinants",
      "subject": "MATEMATICĂ",
      "grade": "11",
      "module": "6. MATEMATICĂ (CLASA A 11-A)",
      "title": "Determinanți de Ordin 2 & 3: Regula lui Sarrus",
      "desc": "Calculul determinanților, proprietăți esențiale (linii nule, comutativitate) și dezvoltarea după o linie.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.sky,
      "tag": "ALGEBRĂ",
    },
    {
      "id": "mat-11-limits",
      "subject": "MATEMATICĂ",
      "grade": "11",
      "module": "6. MATEMATICĂ (CLASA A 11-A)",
      "title": "Analiză: Limite de Funcții & Cazuri de Nedeterminare",
      "desc": "Eliminarea cazurilor 0/0, infinit/infinit, limite fundamentale și regula lui l'Hospital.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.mustard,
      "tag": "ANALIZĂ",
    },

    // =========================================================================
    // CLASA A 12-A (15 ARTICOLE)
    // =========================================================================
    {
      "id": "cpp-12-oop-classes",
      "subject": "C++",
      "grade": "12",
      "module": "1. PROGRAMARE ORIENTATĂ PE OBIECTE (OOP)",
      "title": "OOP în C++: Clase, Obiecte & Modificatori de Acces",
      "desc": "Diferența dintre clasă și instanță, specificatorii public, private și protected, metode membre.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.forest,
      "tag": "OOP",
    },
    {
      "id": "cpp-12-oop-constructors",
      "subject": "C++",
      "grade": "12",
      "module": "1. PROGRAMARE ORIENTATĂ PE OBIECTE (OOP)",
      "title": "Constructori, Destructori & Încapsulare",
      "desc": "Constructorul implicit, constructorul de copiere, lista de inițializare și eliberarea resurselor.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sky,
      "tag": "OOP",
    },
    {
      "id": "cpp-12-oop-inheritance",
      "subject": "C++",
      "grade": "12",
      "module": "1. PROGRAMARE ORIENTATĂ PE OBIECTE (OOP)",
      "title": "Moștenirea în C++ (Inheritance)",
      "desc": "Clasa de bază și clasa derivată, reutilizarea codului și accesul la membrii protejați.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.mustard,
      "tag": "OOP",
    },
    {
      "id": "cpp-12-oop-polymorphism",
      "subject": "C++",
      "grade": "12",
      "module": "1. PROGRAMARE ORIENTATĂ PE OBIECTE (OOP)",
      "title": "Polimorfism & Funcții Virtuale (virtual)",
      "desc": "Legarea dinamică la execuție, clase abstracte și suprascrierea metodelor (override).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.sunset,
      "tag": "OOP",
    },
    {
      "id": "db-12-sql-intro",
      "subject": "C++",
      "grade": "12",
      "module": "2. BAZE DE DATE RELAȚIONALE (SQL)",
      "title": "Baze de Date: Modelul Relațional & Tabele",
      "desc": "Concepte de cheie primară (PRIMARY KEY), cheie străină (FOREIGN KEY) și tipuri de date SQL.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "5 MIN",
      "color": AppColors.forest,
      "tag": "SQL",
    },
    {
      "id": "db-12-sql-select",
      "subject": "C++",
      "grade": "12",
      "module": "2. BAZE DE DATE RELAȚIONALE (SQL)",
      "title": "Interogarea Datelor: Instrucțiunea SELECT",
      "desc": "Filtrarea cu WHERE, clauzele LIKE, BETWEEN, ordonarea cu ORDER BY și eliminarea duplicatelor (DISTINCT).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sky,
      "tag": "SQL",
    },
    {
      "id": "db-12-sql-crud",
      "subject": "C++",
      "grade": "12",
      "module": "2. BAZE DE DATE RELAȚIONALE (SQL)",
      "title": "Comenzile INSERT, UPDATE & DELETE",
      "desc": "Manipularea înregistrărilor din tabele, importanța condiției WHERE la actualizare și ștergere.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "5 MIN",
      "color": AppColors.mustard,
      "tag": "SQL",
    },
    {
      "id": "bac-12-info-sub1",
      "subject": "C++",
      "grade": "12",
      "module": "3. PREGĂTIRE BACALAUREAT (INFORMATICĂ)",
      "title": "Bacalaureat: Strategii pentru Subiectul I (Grile & Expresii)",
      "desc": "Evaluarea expresiilor logice C++, operatori pe biți, matrice și recurențe fără greșeală.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sunset,
      "tag": "BAC",
    },
    {
      "id": "bac-12-info-sub2",
      "subject": "C++",
      "grade": "12",
      "module": "3. PREGĂTIRE BACALAUREAT (INFORMATICĂ)",
      "title": "Bacalaureat: Rezolvarea Eficientă a Subiectului II",
      "desc": "Manipularea șirurilor de caractere, declararea structurilor `struct` și algoritmi pe grafuri/arbori.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.forest,
      "tag": "BAC",
    },
    {
      "id": "bac-12-info-sub3",
      "subject": "C++",
      "grade": "12",
      "module": "3. PREGĂTIRE BACALAUREAT (INFORMATICĂ)",
      "title": "Bacalaureat: Algoritmi Eficienți la Subiectul III (Problema 3)",
      "desc": "Scrierea algoritmilor eficienți ca memorie și timp de execuție: complexitate O(N) și memorie O(1).",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "8 MIN",
      "color": AppColors.sky,
      "tag": "BAC",
    },
    {
      "id": "mat-12-laws",
      "subject": "MATEMATICĂ",
      "grade": "12",
      "module": "4. MATEMATICĂ (STRUCTURI ALGEBRICE)",
      "title": "Legi de Compoziție & Proprietăți Fundamentale",
      "desc": "Parte stabilă, comutativitate, asociativitate, element neutru și elemente simetrizabile.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.mustard,
      "tag": "ALGEBRĂ",
    },
    {
      "id": "mat-12-groups",
      "subject": "MATEMATICĂ",
      "grade": "12",
      "module": "4. MATEMATICĂ (STRUCTURI ALGEBRICE)",
      "title": "Grupuri Comutative (Abeliene) & Morfisme",
      "desc": "Axiomele de grup, ecuații într-un grup, noțiunea de izomorfism de grupuri.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.sunset,
      "tag": "ALGEBRĂ",
    },
    {
      "id": "mat-12-polynomials",
      "subject": "MATEMATICĂ",
      "grade": "12",
      "module": "4. MATEMATICĂ (STRUCTURI ALGEBRICE)",
      "title": "Inele de Polinoame & Relațiile lui Viète",
      "desc": "Împărțirea polinoamelor, schema lui Horner, rădăcini multiple și descompunerea în factori ireductibili.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "7 MIN",
      "color": AppColors.forest,
      "tag": "ALGEBRĂ",
    },
    {
      "id": "mat-12-primitives",
      "subject": "MATEMATICĂ",
      "grade": "12",
      "module": "5. MATEMATICĂ (CALCUL INTEGRAL)",
      "title": "Primitive & Integrale Nedefinite",
      "desc": "Tabelul integralelor imediate, proprietatea de liniaritate a integralei nedefinite.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "6 MIN",
      "color": AppColors.sky,
      "tag": "INTEGRALE",
    },
    {
      "id": "mat-12-definite",
      "subject": "MATEMATICĂ",
      "grade": "12",
      "module": "5. MATEMATICĂ (CALCUL INTEGRAL)",
      "title": "Integrala Definită: Formula Leibniz-Newton & Integrarea prin Părți",
      "desc": "Calculul integralelor definite, metoda schimbării de variabilă și calculul ariilor suprafețelor plane.",
      "author": defaultAuthor,
      "date": defaultDate,
      "readTime": "8 MIN",
      "color": AppColors.mustard,
      "tag": "INTEGRALE",
    },
  ];

  // Specific lectures content dictionary
  static final Map<String, Map<String, dynamic>> curatedLectures = {
    // ---------------- PYTHON 9 ----------------
    "py-9-intro": {
      "tag": "INFORMATICĂ // CLASA A 9-A // PYTHON",
      "title": "Introducere în limbajul Python",
      "subtitle": "Ghidul de start conform noii programe de liceu pentru clasa a 9-a.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. De ce Python în liceu?",
          "text": "Spre deosebire de C++, care impune o sintaxă rigidă cu acolade, punct și virgulă și specificarea strictă a tipurilor de date, Python oferă o sintaxă curată, apropiată de limba engleză. În clasa a 9-a, Python este utilizat pentru a înțelege structura algoritmilor fără barieră sintactică.",
        },
        {
          "heading": "2. Compilare vs. Interpretare",
          "text": "În C++, codul sursă este compilat direct în binar executabil pe procesor. În Python, fișierele .py sunt interpretate linie cu linie de către interpretorul Python, permițând testare rapidă și prototipare dinamică.",
          "code": "# Primul tău program în Python:\nprint(\"Nivelul 1 a început!\")\n\n# Citire de la tastatură:\nnume = input(\"Introdu numele tău de aventurier: \")\nprint(f\"Bun venit în breaslă, {nume}!\")",
          "lang": "python"
        },
        {
          "heading": "3. Regula de Aur: Indentarea PEP 8",
          "text": "În Python NU există acolade { } pentru delimitarea blocurilor! Structurile (if, for, while, funcții) sunt definite exclusiv prin indentare (exact 4 spații). O aliniere incorectă generează un IndentationError.",
          "callout": "ATENȚIE:\nNu amesteca tab-urile cu spațiile! Folosește întotdeauna 4 spații pentru fiecare nivel de indentare conform standardului oficial PEP 8."
        },
      ]
    },
    "py-9-vars": {
      "tag": "INFORMATICĂ // CLASA A 9-A // PYTHON",
      "title": "Variabile, Tipuri Primitive & input()",
      "subtitle": "Cum stocăm și manipulăm datele în memoria programului.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Tipare dinamică în Python",
          "text": "Nu este nevoie să declari tipul unei variabile în avans (ca în C++: int x;). Python asociază tipul automat în funcție de valoarea atribuită.",
        },
        {
          "heading": "2. Tipuri fundamentale de date",
          "text": "• int: Numere întregi pozitive sau negative (fără limită fixă de 32 de biți ca în C++).\n• float: Numere cu virgulă mobilă (reale).\n• str: Șiruri de caractere delimitate prin ghilimele simple sau duble.\n• bool: Valori de adevăr (True sau False).",
          "code": "varsta = 15          # int\ninaltime = 1.75      # float\nnume = \"Alex\"        # str\neste_elev = True     # bool",
          "lang": "python"
        },
        {
          "heading": "3. Funcția input() și conversia de tip (Casting)",
          "text": "Funcția input() returnează întotdeauna un șir de caractere (str). Pentru a face calcule matematice, este obligatoriu să convertim rezultatul cu int() sau float().",
          "code": "a = int(input(\"Introdu a: \"))\nb = int(input(\"Introdu b: \"))\nsuma = a + b\nprint(\"Suma este:\", suma)",
          "lang": "python",
          "callout": "EROARE FRECVENTĂ:\nDacă scrii `a = input()` și `b = input()`, `a + b` va concatena textele (ex: '3' + '5' = '35'), în loc să adune valorile!"
        }
      ]
    },
    "py-9-operators": {
      "tag": "INFORMATICĂ // CLASA A 9-A // PYTHON",
      "title": "Operatori Aritmetici & Logici în Python",
      "subtitle": "Calcul numeric și evaluarea expresiilor booleene.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Operatori Aritmetici Speciali",
          "text": "În Python există doi operatori esențiali diferiți de majoritatea limbajelor:\n• `/` : Împărțire reală (întotdeauna returnează float, ex: 7 / 2 = 3.5)\n• `//` : Împărțire întreagă (ex: 7 // 2 = 3)\n• `%` : Restul împărțirii (modulo, ex: 7 % 2 = 1)\n• `**` : Ridicare la putere (ex: 2 ** 5 = 32)",
          "code": "print(10 // 3)   # Afișează 3\nprint(10 % 3)    # Afișează 1\nprint(2 ** 10)   # Afișează 1024",
          "lang": "python"
        },
        {
          "heading": "2. Operatori Logici: and, or, not",
          "text": "Spre deosebire de C++ (&&, ||, !), în Python operatorii logici sunt cuvinte englezești clare.",
          "code": "x = 15\nif x >= 10 and x <= 20:\n    print(\"Numărul este în intervalul [10, 20]\")",
          "lang": "python"
        }
      ]
    },
    "py-9-if": {
      "tag": "INFORMATICĂ // CLASA A 9-A // PYTHON",
      "title": "Instrucțiunea Decizională: if, elif & else",
      "subtitle": "Cum controlăm fluxul programului folosind decizii logice.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Structura if - elif - else",
          "text": "Permite executarea diferitelor blocuri de instrucțiuni în funcție de evaluarea unei expresii booleene.",
          "code": "nota = int(input(\"Introdu nota obținută: \"))\n\nif nota >= 9:\n    print(\"Excelent! Rang aur.\")\nelif nota >= 7:\n    print(\"Bun! Rang argint.\")\nelif nota >= 5:\n    print(\"Ai trecut examenul.\")\nelse:\n    print(\"Trebuie să reiei quest-ul!\")",
          "lang": "python"
        }
      ]
    },
    "py-9-loops": {
      "tag": "INFORMATICĂ // CLASA A 9-A // PYTHON",
      "title": "Structuri Repetitive: while & for range()",
      "subtitle": "Automatizarea execuției prin cicluri determinate și nedeterminate.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Bucla for cu funcția range()",
          "text": "Funcția `range(start, stop, step)` generează o secvență de numere de la `start` până la `stop - 1`.",
          "code": "# Numerele de la 1 la 10:\nfor i in range(1, 11):\n    print(i, end=' ')\n\n# Numărare descrescătoare:\nfor i in range(10, 0, -1):\n    print(i, end=' ')",
          "lang": "python"
        },
        {
          "heading": "2. Bucla while",
          "text": "Se execută atâta timp cât condiția specificată rămâne adevărată.",
          "code": "n = int(input())\nwhile n > 0:\n    print(n % 10)\n    n //= 10",
          "lang": "python"
        }
      ]
    },

    // ---------------- C++ 9 ----------------
    "cpp-9-intro": {
      "tag": "INFORMATICĂ // CLASA A 9-A // C++",
      "title": "Structura unui Program C++ & iostream",
      "subtitle": "Directiva #include, funcția main() și fluxurile de intrare/ieșire.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Scheletul programului",
          "text": "Fiecare program C++ începe cu includerea bibliotecilor necesare și definirea funcției `main()`, punctul de pornire al execuției.",
          "code": "#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << \"Nivel 1 C++ activat!\" << endl;\n    return 0;\n}",
          "lang": "cpp"
        },
        {
          "heading": "2. Fluxul cin și cout",
          "text": "Pentru afișare folosim operatorul de inserție `<<` cu `cout`, iar pentru citire operatorul de extracție `>>` cu `cin`.",
          "code": "int x, y;\ncin >> x >> y;\ncout << \"Produsul este: \" << x * y << \"\\n\";",
          "lang": "cpp"
        }
      ]
    },
    "alg-9-digits": {
      "tag": "INFORMATICĂ // CLASA A 9-A // C++",
      "title": "Prelucrarea Cifrelor unui Număr",
      "subtitle": "Algoritmul fundamental de izolare și procesare a cifrelor în baza 10.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Izolarea și tăierea ultimei cifre",
          "text": "• `n % 10` : Oferă ultima cifră a numărului.\n• `n = n / 10` : Elimină ultima cifră din număr.",
          "code": "int n;\ncin >> n;\nint suma = 0;\n\nwhile (n > 0) {\n    int cifra = n % 10;\n    suma += cifra;\n    n /= 10;\n}\ncout << \"Suma cifrelor este: \" << suma;",
          "lang": "cpp"
        },
        {
          "heading": "2. Construirea Oglinditului (Inversului)",
          "text": "Înmulțim oglinditul parțial cu 10 și adăugăm noua cifră extrasă.",
          "code": "int oglindit = 0;\nwhile (n > 0) {\n    oglindit = oglindit * 10 + n % 10;\n    n /= 10;\n}",
          "lang": "cpp"
        }
      ]
    },
    "cpp-9-vectors-basic": {
      "tag": "INFORMATICĂ // CLASA A 9-A // C++",
      "title": "Tablouri Unidimensionale (Vectori)",
      "subtitle": "Gestiunea colecțiilor omogene de date indexate de la 0 la n-1.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Ce este un vector?",
          "text": "Un vector este o zonă contiguă de memorie ce conține elemente de același tip. În C++, elementele sunt numerotate începând cu indicele 0.",
          "code": "int v[100]; // declarăm un vector cu maximum 100 de elemente\nint n;\ncin >> n;   // numărul real de elemente\n\nfor (int i = 0; i < n; i++) {\n    cin >> v[i];\n}",
          "lang": "cpp"
        },
        {
          "heading": "2. Maximul dintr-un vector",
          "text": "Inițializăm maximul cu primul element și comparăm secvențial cu restul elementelor.",
          "code": "int maxim = v[0];\nfor (int i = 1; i < n; i++) {\n    if (v[i] > maxim) {\n        maxim = v[i];\n    }\n}\ncout << \"Maximul este: \" << maxim;",
          "lang": "cpp",
          "callout": "SFAT DE COD:\nNu inițializa niciodată maximul cu 0 dacă vectorul poate conține și numere negative! Folosește primul element `v[0]`."
        }
      ]
    },

    // ---------------- CLASA A 10-A ----------------
    "cpp-10-matrix-basics": {
      "tag": "INFORMATICĂ // CLASA A 10-A // C++",
      "title": "Tablouri Bidimensionale (Matrice)",
      "subtitle": "Tabele structurate pe linii și coloane.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Declarare și Parcurgere",
          "text": "O matrice are nevoie de doi indici: primul pentru linie (i) și al doilea pentru coloană (j).",
          "code": "int a[100][100];\nint n, m;\ncin >> n >> m; // n linii, m coloane\n\nfor (int i = 0; i < n; i++) {\n    for (int j = 0; j < m; j++) {\n        cin >> a[i][j];\n    }\n}",
          "lang": "cpp"
        },
        {
          "heading": "2. Diagonalele unei matrice pătratice (n == m)",
          "text": "• Diagonala principală: elementele unde `i == j`\n• Diagonala secundară: elementele unde `i + j == n - 1`",
          "code": "for (int i = 0; i < n; i++) {\n    cout << a[i][i] << \" \"; // Afișează diagonala principală\n}",
          "lang": "cpp"
        }
      ]
    },
    "cpp-10-strings-cstring": {
      "tag": "INFORMATICĂ // CLASA A 10-A // C++",
      "title": "Șiruri de caractere în stil C (cstring)",
      "subtitle": "Tablouri de caractere terminate cu '\\0'.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Funcții esențiale din <cstring>",
          "text": "• `strlen(s)`: Calculează lungimea efectivă a șirului fără '\\0'.\n• `strcpy(dest, src)`: Copiază șirul src în dest.\n• `strcat(dest, src)`: Concatenează src la sfârșitul dest.\n• `strcmp(s1, s2)`: Compară alfabetic două șiruri (0 dacă sunt identice).",
          "code": "#include <iostream>\n#include <cstring>\nusing namespace std;\n\nint main() {\n    char s[100];\n    cin.getline(s, 100);\n    cout << \"Lungime: \" << strlen(s) << endl;\n    return 0;\n}",
          "lang": "cpp"
        }
      ]
    },

    // ---------------- CLASA A 11-A ----------------
    "cpp-11-backtracking-perm": {
      "tag": "INFORMATICĂ // CLASA A 11-A // C++",
      "title": "Generarea Permutărilor cu Backtracking",
      "subtitle": "Modelul clasic al algoritmului de căutare recursivă pe stivă.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Structura algoritmului",
          "text": "Fiecare nivel `k` reprezintă o poziție în permutare. Încercăm toate valorile de la 1 la n și validăm dacă valoarea a mai fost folosită.",
          "code": "int st[20], n;\n\nbool valid(int k) {\n    for (int i = 1; i < k; i++)\n        if (st[i] == st[k]) return false;\n    return true;\n}\n\nvoid bkt(int k) {\n    for (int v = 1; v <= n; v++) {\n        st[k] = v;\n        if (valid(k)) {\n            if (k == n) {\n                for (int i = 1; i <= n; i++) cout << st[i] << \" \";\n                cout << \"\\n\";\n            } else {\n                bkt(k + 1);\n            }\n        }\n    }\n}",
          "lang": "cpp"
        }
      ]
    },
    "cpp-11-graphs-bfs": {
      "tag": "INFORMATICĂ // CLASA A 11-A // C++",
      "title": "Parcurgerea în Lățime a Grafurilor (BFS)",
      "subtitle": "Găsirea distanțelor minime folosind structura de coadă (std::queue).",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Implementarea BFS",
          "text": "Nodul de start este adăugat în coadă și marcat ca vizitat. Cât timp coada nu este vidă, extragem vârful curent și explorăm toți vecinii nevizitați.",
          "code": "void bfs(int start) {\n    queue<int> q;\n    q.push(start);\n    viz[start] = 1;\n    \n    while (!q.empty()) {\n        int nod = q.front();\n        q.pop();\n        cout << nod << \" \";\n        \n        for (int vecin = 1; vecin <= n; vecin++) {\n            if (a[nod][vecin] == 1 && !viz[vecin]) {\n                viz[vecin] = 1;\n                q.push(vecin);\n            }\n        }\n    }\n}",
          "lang": "cpp"
        }
      ]
    },

    // ---------------- CLASA A 12-A ----------------
    "cpp-12-oop-classes": {
      "tag": "INFORMATICĂ // CLASA A 12-A // C++",
      "title": "Programare Orientată pe Obiecte: Clase & Obiecte",
      "subtitle": "Trecerea de la programarea procedurală la arhitectura bazată pe obiecte.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Definirea unei clase",
          "text": "O clasă este un tipar care grupează date (atribute) și funcții (metode) ce operează pe acele date.",
          "code": "class Player {\nprivate:\n    string nume;\n    int exp;\n\npublic:\n    Player(string n) {\n        nume = n;\n        exp = 0;\n    }\n    void addExp(int puncte) {\n        exp += puncte;\n    }\n    void afisare() {\n        cout << nume << \" are \" << exp << \" EXP\\n\";\n    }\n};",
          "lang": "cpp"
        }
      ]
    },
    "bac-12-info-sub3": {
      "tag": "INFORMATICĂ // CLASA A 12-A // BAC",
      "title": "Algoritmi Eficienți la Subiectul III (Problema 3)",
      "subtitle": "Cum obții punctajul maxim pentru eficiență: O(N) timp și O(1) spațiu.",
      "author": defaultAuthor,
      "date": defaultDate,
      "sections": [
        {
          "heading": "1. Regula de Aur pentru Subiectul III.3",
          "text": "Pentru a obține punctajul complet (10 puncte la eficiență), nu este permisă memorarea tuturor numerelor din fișier într-un vector! Datele trebuie procesate direct în timpul citirii (algoritm online / 'on-the-fly').",
          "callout": "IMPORTANT LA BAC:\nExplică întotdeauna algoritmul în cuvinte înaintea codului! Dacă algoritmul este corect dar lipsește justificarea eficienței în limbaj natural, pierzi 2-3 puncte din oficiu."
        },
        {
          "heading": "2. Exemplu tipic: Vectori de frecvență",
          "text": "Când valorile din fișier sunt mici (ex: numere naturale de cel mult 2-3 cifre), folosim un vector de apariții alocat static.",
          "code": "int fr[1000] = {0};\nint x;\nwhile (fin >> x) {\n    if (x >= 10 && x <= 99)\n        fr[x]++;\n}",
          "lang": "cpp"
        }
      ]
    },
  };
}